### ISSUE TITLE
Comparing two meshes

### ISSUE THREAD

**Issue by aellery** [cburstedde/p4est#215]
If I have two meshes that have been refined in different ways, what is the easiest way to compare them to each other? 

For example, if I chose a spatial coordinate (x,y) and then created a p4est_quadrant struct from the first mesh that contains (x,y), what is the easiest way to create a second p4est_quadrant struct corresponding to the same position in the second mesh? Is there way to write a get_quad_at_coords(x,y) function?

**Comment by aellery** [comment]
Nevermind, I worked it out.

**Comment by cburstedde** [comment]
I'm wondering what you mean by "creating a quadrant," since p4est usually does all necessary creation of quadrant structures. Two meshes of different refinement usually are partitioned differently, so you would be looking at a relatively sophisticated parallel algorithm. Would you like to elaborate on your exact problem formulation?

**Comment by cburstedde** [comment]
Bump for comments/clarification.
