### ISSUE TITLE
Visit further neighboring quadrants

### ISSUE THREAD

**Issue by geoclustc** [cburstedde/p4est#25]
Hi,
Is it possible to visit the value of further neighboring points (quadrants) (i+m, j+n) **that don't share the same faces, edges, or corners** when using high order FD to calculate a special point (quadrant)(i,j)? Or are there some interfaces or data structures that can be used in p4est_iterate to achieve this? Can you give me some possible solutions?

Thank you very much!

**Comment by data-panda** [comment]
Hi, 

I am not sure about the finite difference based access but the further neighbors (beyond the neighbor across the face / edge /node) can be done using p4est_mesh_t data structure (p4est_mesh.c / .h ). Once a tree / forest adapts it encodes the neighborhood imformation. Do note that the 2:1 balance only enforces the condition just on the neighbor and not neighbor of the neighbor.

Regards, Aniruddha.

**Comment by geoclustc** [comment]
Thank you, Aniruddha. 
Would you mind providing some examples or other information about how to use p4est_mesh_t ? I have read its reference on http://p4est.github.io/api/index.html but didn't understand that. 
Thank you very much!

**Comment by cburstedde** [comment]
In parallel, you'd need a ghost layer structure that is wider than one element. Please look at p4est_ghost_expand to create it iteratively, layer by layer.

To access neighbors of neighbors, you can do binary searches in the forest and expanded ghost layer to find them. This should work and scale fine, even though it is not the fastest possible way.

Alternatively, you may create the p4est_mesh structure at the expense of some memory and setup time, but with the benefit of doing O(1) lookups. However, it does not allow to look for neighbors of ghosts, so you'd have to extend the structure to include this information for multiple layers of ghosts. This may be difficult since p4est_iterate does not currently iterate over ghosts.

When you have a forest of trees that is not a brick, your numerical method may get confused at corners where 3 or >= 5 trees meet. Did you account for this case?

So maybe it would be easier to allocate a subgrid of dofs in each quadrant, such that only one neighbor quadrant is required to access all relevant dofs. See our arxiv preprints https://arxiv.org/abs/1702.06898 and https://arxiv.org/abs/1703.03116 for the general idea.
