### ISSUE TITLE
Cannot build without mpiexec

### ISSUE THREAD

**Issue by knepley** [cburstedde/p4est#282]
Lisandro Dalcin has an excellent writeup here: https://gitlab.com/petsc/petsc/-/issues/1531

**Comment by tim-griesbach** [comment]
Would you be able to try the latest p4est master branch? Since the error message
```
configure:3709: error: --enable-mpi given but neither mpirun nor mpiexec found
```
should not appear anymore due to the changes in the libsc submodule in the PR https://github.com/cburstedde/libsc/pull/117, which in particular addressed a similar issue. So, this may fix the reported configure issue.

cc @hannesbrandt

**Comment by cburstedde** [comment]
Any comments regarding the develop branches of p4est and libsc? It seems that mpirun/mpiexec are not required anymore.

**Comment by cburstedde** [comment]
Any news on compatibility? About to release 2.8.6 very soon.

**Comment by knepley** [comment]
Yes, the fix works. We closed the issue: https://gitlab.com/petsc/petsc/-/issues/1531
