### ISSUE TITLE
Hanging Nodes

### ISSUE THREAD

**Issue by esys-escript** [cburstedde/p4est#70]
Is there any way to create an lnodes structure from a p4est that numbers the hanging nodes in the p4est?

**Comment by cburstedde** [comment]
We only number the independent (i.e. non-hanging) nodes globally. We make no effort to establish global consistency for hanging nodes since that is usually not needed.

You may check out the p4est_iterate function, however, which will allow you to identify all hanging face or edge situations. Hopefully that gives you the functionality you need.

If you need to make hanging node numbers globally consistent, you could use a hash table or define an ownership rule that assigns an owner process to each, but I'd caution against it.
